# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- vendor

# 2. Installed plugin gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji
- github-pages

# 3. Gem settings
sass:
  style: compressed
  sass_dir: _sass

paginate: 8 # jekyll-paginate > items per page
paginate_path: "/blog/page:num/" # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # base url for jekyll mentions

compress_html:
  clippings: all

author: Winnie Yeung # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Winnie Yeung # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.linkedin.com/in/winnieyeung
    - https://plus.google.com/+KunalBaweja
    - https://github.com/vionwinnie

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: /:categories/:title/  # define url construction
timezone: America/New_York # Timezone for blog posts and alike

# 6. Site wide defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/img/winnie-logo.png" # Default image for sharing

  - scope:
      path: ""
      type: posts
    values:
      layout: post

  - scope:
      path: ""
      type: tag
    values:
      layout: tag
collections:
  tag:
      output: true

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Winnie Yeung" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/img/winnie-logo.png" # Site logo, also used in jekyll-seo-tag

# Site description and default description, also used in jekyll-seo-tag
url: "https://vionwinnie.github.io" # Site url, also used in jekyll-seo-tag
repo: "https://github.com/vionwinnie/bawejakunal.github.io"
disqus: "vionwinnie-github-io"
avatarurl: "https://github.com/vionwinnie.png"

# site verification
webmaster_verifications:
  google: sCRGg28ReGiDdQ4JQ75b6RCTtmBD9J6QQwh1kpIMDAU

# default markdown processor and highlighter
markdown: kramdown
highlighter: rouge
error_mode: strict

# 8. Site navigation
navigation_header:
  Home: /
  About: /about/
  Blog: /blog/

#site credits
navigation_footer:
  Adopted Alembic Theme: https://alembic.darn.es/

contact:
  email:      dcvionwinnie@gmail.com
  github:     https://github.com/vionwinnie
  linkedin:   https://www.linkedin.com/in/winnieyeung
  
schools:
  georgiatech: https://www.analytics.gatech.edu/
  middlebury: http://www.middlebury.edu/academics/hist
